[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.images"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/G5andeepD/module-ballerinax-openai-images"

[build-options]
observabilityIncluded = true